"""empty message

Revision ID: 22c7c0611448
Revises: 9452402e522b
Create Date: 2018-04-03 00:40:47.294158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22c7c0611448'
down_revision = '9452402e522b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'branch_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('student', 'category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_unique_constraint(None, 'student', ['student_id'])
    op.create_foreign_key(None, 'student', 'branch', ['branch_id'], ['id'])
    op.create_foreign_key(None, 'student', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='unique')
    op.alter_column('student', 'category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('student', 'branch_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
