"""empty message

Revision ID: 4519f58b98f5
Revises: 0203bc4daadc
Create Date: 2018-02-23 00:00:02.906395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4519f58b98f5'
down_revision = '0203bc4daadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'punchIn',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('attendance', 'punchOut',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'punchOut',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('attendance', 'punchIn',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
