"""empty message

Revision ID: 54a8ee4ee8e7
Revises: 7525346b05a7
Create Date: 2018-05-28 23:59:36.602196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a8ee4ee8e7'
down_revision = '7525346b05a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(length=50), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'student_id', name='student_test_uc')
    )
    op.add_column(u'category', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'branch', ['branch_id'], ['id'])
    op.add_column(u'exam', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exam', 'branch', ['branch_id'], ['id'])
    op.add_column(u'faculty', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'faculty', 'branch', ['branch_id'], ['id'])
    op.add_column(u'grade', sa.Column('branch_id', sa.Integer(), nullable=False))
    op.add_column(u'grade', sa.Column('comment', sa.String(length=50), nullable=True))
    op.add_column(u'grade', sa.Column('grade', sa.String(length=5), nullable=False))
    op.add_column(u'grade', sa.Column('lower', sa.Integer(), nullable=False))
    op.add_column(u'grade', sa.Column('upper', sa.Integer(), nullable=False))
    op.create_unique_constraint('branch_grade_uc', 'grade', ['branch_id', 'grade'])
    op.create_unique_constraint('lower_upper_uc', 'grade', ['lower', 'upper'])
    op.create_foreign_key(None, 'grade', 'branch', ['branch_id'], ['id'])
    op.add_column(u'subject', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subject', 'branch', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_column(u'subject', 'branch_id')
    op.drop_constraint(None, 'grade', type_='foreignkey')
    op.drop_constraint('lower_upper_uc', 'grade', type_='unique')
    op.drop_constraint('branch_grade_uc', 'grade', type_='unique')
    op.drop_column(u'grade', 'upper')
    op.drop_column(u'grade', 'lower')
    op.drop_column(u'grade', 'grade')
    op.drop_column(u'grade', 'comment')
    op.drop_column(u'grade', 'branch_id')
    op.drop_constraint(None, 'faculty', type_='foreignkey')
    op.drop_column(u'faculty', 'branch_id')
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.drop_column(u'exam', 'branch_id')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column(u'category', 'branch_id')
    op.drop_table('marks')
    # ### end Alembic commands ###
