"""empty message

Revision ID: 5b50adefdef7
Revises: 7e7b17d5aef9
Create Date: 2018-03-24 00:28:23.792224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b50adefdef7'
down_revision = '7e7b17d5aef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_attendance_per_day_student', 'attendance', ['date', 'student_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_attendance_per_day_student', 'attendance', type_='unique')
    # ### end Alembic commands ###
