"""empty message

Revision ID: 7525346b05a7
Revises: 8ebaaba69488
Create Date: 2018-05-28 04:43:32.431791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7525346b05a7'
down_revision = '8ebaaba69488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('evaluator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test', 'faculty', ['evaluator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test', type_='foreignkey')
    op.drop_column('test', 'evaluator_id')
    # ### end Alembic commands ###
