"""empty message

Revision ID: 7e7b17d5aef9
Revises: 3da172d991d5
Create Date: 2018-03-10 14:23:00.272116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7b17d5aef9'
down_revision = '3da172d991d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'punch_in',
               existing_type=sa.TEXT(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'punch_in',
               existing_type=sa.TEXT(length=50),
               nullable=False)
    # ### end Alembic commands ###
