"""empty message

Revision ID: a185989f4a14
Revises: 20f1b60d2a31
Create Date: 2019-08-05 03:18:58.803549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a185989f4a14'
down_revision = '20f1b60d2a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faculty', 'facultyId',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('subject', sa.Column('short_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject', 'short_name')
    op.alter_column('faculty', 'facultyId',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
