"""empty message

Revision ID: aae82804e7b0
Revises: f251b41d9004
Create Date: 2018-07-28 01:44:38.700765

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'aae82804e7b0'
down_revision = 'f251b41d9004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
