"""empty message

Revision ID: bf30825c1e23
Revises: aae82804e7b0
Create Date: 2018-07-29 17:44:58.358649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf30825c1e23'
down_revision = 'aae82804e7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('std_test_association', 'exam_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('std_test_association', 'student_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('std_test_association', 'test_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('std_test_association', 'test_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('std_test_association', 'student_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('std_test_association', 'exam_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
