"""empty message

Revision ID: c04f5e3c4ea0
Revises: 5b50adefdef7
Create Date: 2018-04-01 11:23:21.875934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04f5e3c4ea0'
down_revision = '5b50adefdef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('superUser', sa.Boolean(), nullable=True))
    op.add_column('student', sa.Column('superUser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'superUser')
    op.drop_column('faculty', 'superUser')
    # ### end Alembic commands ###
