"""empty message

Revision ID: d62e27032709
Revises: e7d6e3f6aac0
Create Date: 2018-05-23 01:40:55.698196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62e27032709'
down_revision = 'e7d6e3f6aac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('category_student_uc', 'association', ['left_id', 'right_id'])
    op.drop_index('_category_student_uc', table_name='association')
    op.add_column('test', sa.Column('cat_sub_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test', 'association', ['cat_sub_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test', type_='foreignkey')
    op.drop_column('test', 'cat_sub_id')
    op.create_index('_category_student_uc', 'association', ['left_id', 'right_id'], unique=True)
    op.drop_constraint('category_student_uc', 'association', type_='unique')
    # ### end Alembic commands ###
