"""empty message

Revision ID: e7d6e3f6aac0
Revises: 22c7c0611448
Create Date: 2018-05-14 02:47:29.320918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d6e3f6aac0'
down_revision = '22c7c0611448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('effective_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'effective_end_date')
    # ### end Alembic commands ###
