"""empty message

Revision ID: f9bc2f9a690d
Revises: fa4f8531db8c
Create Date: 2018-02-24 01:53:00.709060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9bc2f9a690d'
down_revision = 'fa4f8531db8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'branch',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('student', 'contact',
               existing_type=sa.TEXT(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'contact',
               existing_type=sa.TEXT(length=50),
               nullable=True)
    op.alter_column('student', 'branch',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
