name: Unittest
on:
  push:
    branches: [master, feature/django]
  pull_request:
    branches: [master, feature/django]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev
      - name: Run Lint
        run: |
          pipenv run black --check --diff .
      - name: Run Tests
        run: |
          pipenv run coverage run --source='.' manage.py test api.tests
          pipenv run coverage xml --omit=phoenix/*,manage.py
        env:
          SECRET_KEY: testingsecretkey
          DEBUG: True
          CORS_ORIGIN_WHITELIST: http://localhost:8000
          DATABASE_URL: sqlite:///db.sqlite3
      - name: Upload Unittest Coverage Report
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
